"""curriculum tables

Revision ID: ff0160a7831b
Revises: 0001
Created: 2026-08-15 05:38:33.903069
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = "0002"
down_revision: str | None = "0001"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "courses",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("content_id", sa.String(length=120), nullable=False),
        sa.Column("slug", sa.String(length=80), nullable=False),
        sa.Column("code", sa.String(length=4), nullable=False),
        sa.Column("title", sa.String(length=140), nullable=False),
        sa.Column("summary", sa.Text(), nullable=False),
        sa.Column("track", sa.String(length=60), nullable=False),
        sa.Column("levels", postgresql.ARRAY(sa.String(length=2)), nullable=False),
        sa.Column("estimated_hours", sa.Integer(), nullable=False),
        sa.Column("order", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_courses")),
        sa.UniqueConstraint("content_id", name=op.f("uq_courses_content_id")),
        sa.UniqueConstraint("slug", name=op.f("uq_courses_slug")),
    )
    op.create_table(
        "learning_paths",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("content_id", sa.String(length=120), nullable=False),
        sa.Column("slug", sa.String(length=80), nullable=False),
        sa.Column("title", sa.String(length=140), nullable=False),
        sa.Column("summary", sa.Text(), nullable=False),
        sa.Column("created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_learning_paths")),
        sa.UniqueConstraint("content_id", name=op.f("uq_learning_paths_content_id")),
        sa.UniqueConstraint("slug", name=op.f("uq_learning_paths_slug")),
    )
    op.create_table(
        "modules",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("content_id", sa.String(length=120), nullable=False),
        sa.Column("course_id", sa.UUID(), nullable=False),
        sa.Column("slug", sa.String(length=80), nullable=False),
        sa.Column("title", sa.String(length=140), nullable=False),
        sa.Column("summary", sa.Text(), nullable=False),
        sa.Column("order", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(
            ["course_id"],
            ["courses.id"],
            name=op.f("fk_modules_course_id_courses"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_modules")),
        sa.UniqueConstraint("content_id", name=op.f("uq_modules_content_id")),
        sa.UniqueConstraint("course_id", "slug", name="uq_modules_course_id_slug"),
    )
    op.create_index(op.f("ix_modules_course_id"), "modules", ["course_id"], unique=False)
    op.create_table(
        "path_courses",
        sa.Column("path_id", sa.UUID(), nullable=False),
        sa.Column("course_id", sa.UUID(), nullable=False),
        sa.Column("order", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["course_id"],
            ["courses.id"],
            name=op.f("fk_path_courses_course_id_courses"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["path_id"],
            ["learning_paths.id"],
            name=op.f("fk_path_courses_path_id_learning_paths"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("path_id", "course_id", name=op.f("pk_path_courses")),
    )
    op.create_table(
        "topics",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("content_id", sa.String(length=120), nullable=False),
        sa.Column("module_id", sa.UUID(), nullable=False),
        sa.Column("slug", sa.String(length=80), nullable=False),
        sa.Column("title", sa.String(length=140), nullable=False),
        sa.Column("summary", sa.Text(), nullable=False),
        sa.Column("order", sa.Integer(), nullable=False),
        sa.Column("levels", postgresql.ARRAY(sa.String(length=2)), nullable=False),
        sa.Column("estimated_minutes", sa.Integer(), nullable=False),
        sa.Column("status", sa.String(length=16), nullable=False),
        sa.Column("tags", postgresql.ARRAY(sa.String(length=80)), nullable=False),
        sa.Column("terminology", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("foreshadows", postgresql.ARRAY(sa.Text()), nullable=False),
        sa.Column("content_hash", sa.String(length=64), nullable=False),
        sa.Column("created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(
            ["module_id"],
            ["modules.id"],
            name=op.f("fk_topics_module_id_modules"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_topics")),
        sa.UniqueConstraint("content_id", name=op.f("uq_topics_content_id")),
        sa.UniqueConstraint("slug", name=op.f("uq_topics_slug")),
    )
    op.create_index(op.f("ix_topics_module_id"), "topics", ["module_id"], unique=False)
    op.create_table(
        "glossary_terms",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("term", sa.String(length=80), nullable=False),
        sa.Column("definition", sa.Text(), nullable=False),
        sa.Column("defined_in_topic_id", sa.UUID(), nullable=True),
        sa.ForeignKeyConstraint(
            ["defined_in_topic_id"],
            ["topics.id"],
            name=op.f("fk_glossary_terms_defined_in_topic_id_topics"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_glossary_terms")),
        sa.UniqueConstraint("term", name=op.f("uq_glossary_terms_term")),
    )
    op.create_table(
        "labs",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("content_id", sa.String(length=120), nullable=False),
        sa.Column("topic_id", sa.UUID(), nullable=False),
        sa.Column("slug", sa.String(length=80), nullable=False),
        sa.Column("title", sa.String(length=140), nullable=False),
        sa.Column("type", sa.String(length=20), nullable=False),
        sa.Column("tier", sa.Integer(), nullable=False),
        sa.Column("image", sa.String(length=120), nullable=False),
        sa.Column("duration_minutes", sa.Integer(), nullable=False),
        sa.Column("order", sa.Integer(), nullable=False),
        sa.Column("objectives", postgresql.ARRAY(sa.Text()), nullable=False),
        sa.Column("spec", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.ForeignKeyConstraint(
            ["topic_id"], ["topics.id"], name=op.f("fk_labs_topic_id_topics"), ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_labs")),
        sa.UniqueConstraint("content_id", name=op.f("uq_labs_content_id")),
    )
    op.create_index(op.f("ix_labs_topic_id"), "labs", ["topic_id"], unique=False)
    op.create_table(
        "lessons",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("topic_id", sa.UUID(), nullable=False),
        sa.Column("section", sa.String(length=80), nullable=False),
        sa.Column("title", sa.String(length=160), nullable=False),
        sa.Column("mode", sa.String(length=16), nullable=False),
        sa.Column("order", sa.Integer(), nullable=False),
        sa.Column("body_md", sa.Text(), nullable=False),
        sa.Column("content_hash", sa.String(length=64), nullable=False),
        sa.ForeignKeyConstraint(
            ["topic_id"], ["topics.id"], name=op.f("fk_lessons_topic_id_topics"), ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_lessons")),
        sa.UniqueConstraint("topic_id", "section", name="uq_lessons_topic_id_section"),
    )
    op.create_index(op.f("ix_lessons_topic_id"), "lessons", ["topic_id"], unique=False)
    op.create_table(
        "objectives",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("topic_id", sa.UUID(), nullable=False),
        sa.Column("code", sa.String(length=40), nullable=False),
        sa.Column("level", sa.String(length=2), nullable=False),
        sa.Column("verb", sa.String(length=30), nullable=False),
        sa.Column("statement", sa.Text(), nullable=False),
        sa.Column("assessed_by", postgresql.ARRAY(sa.Text()), nullable=False),
        sa.ForeignKeyConstraint(
            ["topic_id"],
            ["topics.id"],
            name=op.f("fk_objectives_topic_id_topics"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_objectives")),
        sa.UniqueConstraint("topic_id", "code", name="uq_objectives_topic_id_code"),
    )
    op.create_index(op.f("ix_objectives_topic_id"), "objectives", ["topic_id"], unique=False)
    op.create_table(
        "prerequisites",
        sa.Column("topic_id", sa.UUID(), nullable=False),
        sa.Column("requires_topic_id", sa.UUID(), nullable=False),
        sa.Column("hardness", sa.String(length=16), nullable=False),
        sa.ForeignKeyConstraint(
            ["requires_topic_id"],
            ["topics.id"],
            name=op.f("fk_prerequisites_requires_topic_id_topics"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["topic_id"],
            ["topics.id"],
            name=op.f("fk_prerequisites_topic_id_topics"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("topic_id", "requires_topic_id", name=op.f("pk_prerequisites")),
    )
    op.create_table(
        "quizzes",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("content_id", sa.String(length=120), nullable=False),
        sa.Column("topic_id", sa.UUID(), nullable=False),
        sa.Column("pass_score", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["topic_id"], ["topics.id"], name=op.f("fk_quizzes_topic_id_topics"), ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_quizzes")),
        sa.UniqueConstraint("content_id", name=op.f("uq_quizzes_content_id")),
        sa.UniqueConstraint("topic_id", name=op.f("uq_quizzes_topic_id")),
    )
    op.create_table(
        "topic_items",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("topic_id", sa.UUID(), nullable=False),
        sa.Column("kind", sa.String(length=24), nullable=False),
        sa.Column("content_id", sa.String(length=160), nullable=False),
        sa.Column("title", sa.String(length=200), nullable=False),
        sa.Column("level", sa.String(length=2), nullable=True),
        sa.Column("order", sa.Integer(), nullable=False),
        sa.Column("objectives", postgresql.ARRAY(sa.Text()), nullable=False),
        sa.Column("payload", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("solution", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.ForeignKeyConstraint(
            ["topic_id"],
            ["topics.id"],
            name=op.f("fk_topic_items_topic_id_topics"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_topic_items")),
        sa.UniqueConstraint("topic_id", "kind", "content_id", name="uq_topic_items_identity"),
    )
    op.create_index(op.f("ix_topic_items_topic_id"), "topic_items", ["topic_id"], unique=False)
    op.create_index("ix_topic_items_topic_kind", "topic_items", ["topic_id", "kind"], unique=False)
    op.create_table(
        "quiz_questions",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("quiz_id", sa.UUID(), nullable=False),
        sa.Column("code", sa.String(length=10), nullable=False),
        sa.Column("type", sa.String(length=20), nullable=False),
        sa.Column("level", sa.String(length=2), nullable=False),
        sa.Column("order", sa.Integer(), nullable=False),
        sa.Column("stem", sa.Text(), nullable=False),
        sa.Column("objectives", postgresql.ARRAY(sa.Text()), nullable=False),
        sa.Column("explanation", sa.Text(), nullable=False),
        sa.ForeignKeyConstraint(
            ["quiz_id"],
            ["quizzes.id"],
            name=op.f("fk_quiz_questions_quiz_id_quizzes"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_quiz_questions")),
        sa.UniqueConstraint("quiz_id", "code", name="uq_quiz_questions_quiz_id_code"),
    )
    op.create_index(op.f("ix_quiz_questions_quiz_id"), "quiz_questions", ["quiz_id"], unique=False)
    op.create_table(
        "quiz_options",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("question_id", sa.UUID(), nullable=False),
        sa.Column("code", sa.String(length=2), nullable=False),
        sa.Column("text", sa.Text(), nullable=False),
        sa.Column("is_correct", sa.Boolean(), nullable=False),
        sa.Column("note", sa.Text(), nullable=True),
        sa.ForeignKeyConstraint(
            ["question_id"],
            ["quiz_questions.id"],
            name=op.f("fk_quiz_options_question_id_quiz_questions"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_quiz_options")),
        sa.UniqueConstraint("question_id", "code", name="uq_quiz_options_question_id_code"),
    )
    op.create_index(
        op.f("ix_quiz_options_question_id"), "quiz_options", ["question_id"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_quiz_options_question_id"), table_name="quiz_options")
    op.drop_table("quiz_options")
    op.drop_index(op.f("ix_quiz_questions_quiz_id"), table_name="quiz_questions")
    op.drop_table("quiz_questions")
    op.drop_index("ix_topic_items_topic_kind", table_name="topic_items")
    op.drop_index(op.f("ix_topic_items_topic_id"), table_name="topic_items")
    op.drop_table("topic_items")
    op.drop_table("quizzes")
    op.drop_table("prerequisites")
    op.drop_index(op.f("ix_objectives_topic_id"), table_name="objectives")
    op.drop_table("objectives")
    op.drop_index(op.f("ix_lessons_topic_id"), table_name="lessons")
    op.drop_table("lessons")
    op.drop_index(op.f("ix_labs_topic_id"), table_name="labs")
    op.drop_table("labs")
    op.drop_table("glossary_terms")
    op.drop_index(op.f("ix_topics_module_id"), table_name="topics")
    op.drop_table("topics")
    op.drop_table("path_courses")
    op.drop_index(op.f("ix_modules_course_id"), table_name="modules")
    op.drop_table("modules")
    op.drop_table("learning_paths")
    op.drop_table("courses")
    # ### end Alembic commands ###
